package com.covoiturage.base;

import java.io.Serializable;


/**
 * This class has been automatically generated by Hibernate Synchronizer.
 * For more information or documentation, visit The Hibernate Synchronizer page
 * at http://www.binamics.com/hibernatesync or contact Joe Hudson at joe@binamics.com.
 *
 * This is an object that contains data related to the district table.
 * Do not modify this class because it will be overwritten if the configuration file
 * related to this class is modified.
 *
 * @hibernate.class
 *  table="district"
 */
public abstract class BaseDistrict  implements Serializable {

	public static String PROP_NOM = "Nom";
	public static String PROP_DISTRICT_I_D = "DistrictID";
	public static String PROP_VILLE_I_D = "VilleID";


	private int hashCode = Integer.MIN_VALUE;

	// primary key
	private java.lang.Integer _districtID;

	// fields
	private java.lang.String _nom;
	private com.covoiturage.Ville _villeID;

	// collections
	private java.util.Set _communeSet;


	// constructors
	public BaseDistrict () {
		initialize();
	}

	/**
	 * Constructor for primary key
	 */
	public BaseDistrict (java.lang.Integer _districtID) {
		this.setDistrictID(_districtID);
		initialize();
	}

	/**
	 * Constructor for required fields
	 */
	public BaseDistrict (
		java.lang.Integer _districtID,
		com.covoiturage.Ville _villeID) {

		this.setDistrictID(_districtID);
		this.setVilleID(_villeID);
		initialize();
	}

	protected void initialize () {}



	/**
	 * Return the unique identifier of this class
     * @hibernate.id
     *  generator-class="identity"
     *  column="DistrictID"
     */
	public java.lang.Integer getDistrictID () {
		return _districtID;
	}

	/**
	 * Set the unique identifier of this class
	 * @param _districtID the new ID
	 */
	public void setDistrictID (java.lang.Integer _districtID) {
		this._districtID = _districtID;
		this.hashCode = Integer.MIN_VALUE;
	}


	/**
	 * Return the value associated with the column: Nom
	 */
	public java.lang.String getNom () {
		return _nom;
	}

	/**
	 * Set the value related to the column: Nom
	 * @param _nom the Nom value
	 */
	public void setNom (java.lang.String _nom) {
		this._nom = _nom;
	}


	/**
	 * Return the value associated with the column: VilleID
	 */
	public com.covoiturage.Ville getVilleID () {
		return _villeID;
	}

	/**
	 * Set the value related to the column: VilleID
	 * @param _villeID the VilleID value
	 */
	public void setVilleID (com.covoiturage.Ville _villeID) {
		this._villeID = _villeID;
	}


	/**
	 * Return the value associated with the column: CommuneSet
	 */
	public java.util.Set getCommuneSet () {
		return this._communeSet;
	}

	/**
	 * Set the value related to the column: CommuneSet
	 * @param _communeSet the CommuneSet value
	 */
	public void setCommuneSet (java.util.Set _communeSet) {
		this._communeSet = _communeSet;
	}
	
	public void addToCommuneSet (Object obj) {
		if (null == this._communeSet) this._communeSet = new java.util.HashSet();
		this._communeSet.add(obj);
	}



	public boolean equals (Object obj) {
		if (null == obj) return false;
		if (!(obj instanceof com.covoiturage.base.BaseDistrict)) return false;
		else {
			com.covoiturage.base.BaseDistrict mObj = (com.covoiturage.base.BaseDistrict) obj;
			if (null == this.getDistrictID() || null == mObj.getDistrictID()) return false;
			else return (this.getDistrictID().equals(mObj.getDistrictID()));
		}
	}


	public int hashCode () {
		if (Integer.MIN_VALUE == this.hashCode) {
			if (null == this.getDistrictID()) return super.hashCode();
			else {
				String hashStr = this.getClass().getName() + ":" + this.getDistrictID().hashCode();
				this.hashCode = hashStr.hashCode();
			}
		}
		return this.hashCode;
	}


	public String toString () {
		return super.toString();
	}

}