package com.covoiturage.base;

import java.io.Serializable;


/**
 * This class has been automatically generated by Hibernate Synchronizer.
 * For more information or documentation, visit The Hibernate Synchronizer page
 * at http://www.binamics.com/hibernatesync or contact Joe Hudson at joe@binamics.com.
 *
 * This is an object that contains data related to the rue table.
 * Do not modify this class because it will be overwritten if the configuration file
 * related to this class is modified.
 *
 * @hibernate.class
 *  table="rue"
 */
public abstract class BaseRue  implements Serializable {

	public static String PROP_NOM = "Nom";
	public static String PROP_COMMUNE_I_D = "CommuneID";
	public static String PROP_RUE_I_D = "RueID";
	public static String PROP_POSITION = "Position";


	private int hashCode = Integer.MIN_VALUE;

	// primary key
	private java.lang.Integer _rueID;

	// fields
	private java.lang.String _nom;
	private java.lang.String _position;

	// many to one
	private com.covoiturage.Commune _communeID;


	// constructors
	public BaseRue () {
		initialize();
	}

	/**
	 * Constructor for primary key
	 */
	public BaseRue (java.lang.Integer _rueID) {
		this.setRueID(_rueID);
		initialize();
	}

	/**
	 * Constructor for required fields
	 */
	public BaseRue (
		java.lang.Integer _rueID,
		com.covoiturage.Commune _communeID) {

		this.setRueID(_rueID);
		this.setCommuneID(_communeID);
		initialize();
	}

	protected void initialize () {}



	/**
	 * Return the unique identifier of this class
     * @hibernate.id
     *  generator-class="identity"
     *  column="RueID"
     */
	public java.lang.Integer getRueID () {
		return _rueID;
	}

	/**
	 * Set the unique identifier of this class
	 * @param _rueID the new ID
	 */
	public void setRueID (java.lang.Integer _rueID) {
		this._rueID = _rueID;
		this.hashCode = Integer.MIN_VALUE;
	}


	/**
	 * Return the value associated with the column: Nom
	 */
	public java.lang.String getNom () {
		return _nom;
	}

	/**
	 * Set the value related to the column: Nom
	 * @param _nom the Nom value
	 */
	public void setNom (java.lang.String _nom) {
		this._nom = _nom;
	}


	/**
	 * Return the value associated with the column: Position
	 */
	public java.lang.String getPosition () {
		return _position;
	}

	/**
	 * Set the value related to the column: Position
	 * @param _position the Position value
	 */
	public void setPosition (java.lang.String _position) {
		this._position = _position;
	}


	/**
     * @hibernate.property
     *  column=CommuneID
	 * not-null=true
	 */
	public com.covoiturage.Commune getCommuneID () {
		return this._communeID;
	}

	/**
	 * Set the value related to the column: CommuneID
	 * @param _communeID the CommuneID value
	 */
	public void setCommuneID (com.covoiturage.Commune _communeID) {
		this._communeID = _communeID;
	}


	public boolean equals (Object obj) {
		if (null == obj) return false;
		if (!(obj instanceof com.covoiturage.base.BaseRue)) return false;
		else {
			com.covoiturage.base.BaseRue mObj = (com.covoiturage.base.BaseRue) obj;
			if (null == this.getRueID() || null == mObj.getRueID()) return false;
			else return (this.getRueID().equals(mObj.getRueID()));
		}
	}


	public int hashCode () {
		if (Integer.MIN_VALUE == this.hashCode) {
			if (null == this.getRueID()) return super.hashCode();
			else {
				String hashStr = this.getClass().getName() + ":" + this.getRueID().hashCode();
				this.hashCode = hashStr.hashCode();
			}
		}
		return this.hashCode;
	}


	public String toString () {
		return super.toString();
	}

}