package com.covoiturage.base;

import java.io.Serializable;


/**
 * This class has been automatically generated by Hibernate Synchronizer.
 * For more information or documentation, visit The Hibernate Synchronizer page
 * at http://www.binamics.com/hibernatesync or contact Joe Hudson at joe@binamics.com.
 *
 * This is an object that contains data related to the compte table.
 * Do not modify this class because it will be overwritten if the configuration file
 * related to this class is modified.
 *
 * @hibernate.class
 *  table="compte"
 */
public abstract class BaseCompte  implements Serializable {

	public static String PROP_LOGIN = "Login";
	public static String PROP_TYPE = "Type";
	public static String PROP_PASSWORD = "Password";
	public static String PROP_UTILISATEUR_I_D = "UtilisateurID";
	public static String PROP_AVATAR = "Avatar";


	private int hashCode = Integer.MIN_VALUE;

	// primary key
	private java.lang.String _login;

	// fields
	private java.lang.String _type;
	private java.lang.String _password;
	private java.lang.String _avatar;

	// many to one
	private com.covoiturage.Utilisateur _utilisateurID;


	// constructors
	public BaseCompte () {
		initialize();
	}

	/**
	 * Constructor for primary key
	 */
	public BaseCompte (java.lang.String _login) {
		this.setLogin(_login);
		initialize();
	}

	/**
	 * Constructor for required fields
	 */
	public BaseCompte (
		java.lang.String _login,
		com.covoiturage.Utilisateur _utilisateurID) {

		this.setLogin(_login);
		this.setUtilisateurID(_utilisateurID);
		initialize();
	}

	protected void initialize () {}



	/**
	 * Return the unique identifier of this class
     * @hibernate.id
     *  generator-class="identity"
     *  column="Login"
     */
	public java.lang.String getLogin () {
		return _login;
	}

	/**
	 * Set the unique identifier of this class
	 * @param _login the new ID
	 */
	public void setLogin (java.lang.String _login) {
		this._login = _login;
		this.hashCode = Integer.MIN_VALUE;
	}


	/**
	 * Return the value associated with the column: Type
	 */
	public java.lang.String getType () {
		return _type;
	}

	/**
	 * Set the value related to the column: Type
	 * @param _type the Type value
	 */
	public void setType (java.lang.String _type) {
		this._type = _type;
	}


	/**
	 * Return the value associated with the column: Password
	 */
	public java.lang.String getPassword () {
		return _password;
	}

	/**
	 * Set the value related to the column: Password
	 * @param _password the Password value
	 */
	public void setPassword (java.lang.String _password) {
		this._password = _password;
	}


	/**
	 * Return the value associated with the column: Avatar
	 */
	public java.lang.String getAvatar () {
		return _avatar;
	}

	/**
	 * Set the value related to the column: Avatar
	 * @param _avatar the Avatar value
	 */
	public void setAvatar (java.lang.String _avatar) {
		this._avatar = _avatar;
	}


	/**
     * @hibernate.property
     *  column=UtilisateurID
	 * not-null=true
	 */
	public com.covoiturage.Utilisateur getUtilisateurID () {
		return this._utilisateurID;
	}

	/**
	 * Set the value related to the column: UtilisateurID
	 * @param _utilisateurID the UtilisateurID value
	 */
	public void setUtilisateurID (com.covoiturage.Utilisateur _utilisateurID) {
		this._utilisateurID = _utilisateurID;
	}


	public boolean equals (Object obj) {
		if (null == obj) return false;
		if (!(obj instanceof com.covoiturage.base.BaseCompte)) return false;
		else {
			com.covoiturage.base.BaseCompte mObj = (com.covoiturage.base.BaseCompte) obj;
			if (null == this.getLogin() || null == mObj.getLogin()) return false;
			else return (this.getLogin().equals(mObj.getLogin()));
		}
	}


	public int hashCode () {
		if (Integer.MIN_VALUE == this.hashCode) {
			if (null == this.getLogin()) return super.hashCode();
			else {
				String hashStr = this.getClass().getName() + ":" + this.getLogin().hashCode();
				this.hashCode = hashStr.hashCode();
			}
		}
		return this.hashCode;
	}


	public String toString () {
		return super.toString();
	}

}