package com.covoiturage.base;

import java.io.Serializable;


/**
 * This class has been automatically generated by Hibernate Synchronizer.
 * For more information or documentation, visit The Hibernate Synchronizer page
 * at http://www.binamics.com/hibernatesync or contact Joe Hudson at joe@binamics.com.
 *
 * This is an object that contains data related to the commune table.
 * Do not modify this class because it will be overwritten if the configuration file
 * related to this class is modified.
 *
 * @hibernate.class
 *  table="commune"
 */
public abstract class BaseCommune  implements Serializable {

	public static String PROP_NOM = "Nom";
	public static String PROP_COMMUNE_I_D = "CommuneID";
	public static String PROP_DISTRICT_I_D = "DistrictID";


	private int hashCode = Integer.MIN_VALUE;

	// primary key
	private java.lang.Integer _communeID;

	// fields
	private java.lang.String _nom;

	// many to one
	private com.covoiturage.District _districtID;

	// collections
	private java.util.Set _rueSet;


	// constructors
	public BaseCommune () {
		initialize();
	}

	/**
	 * Constructor for primary key
	 */
	public BaseCommune (java.lang.Integer _communeID) {
		this.setCommuneID(_communeID);
		initialize();
	}

	/**
	 * Constructor for required fields
	 */
	public BaseCommune (
		java.lang.Integer _communeID,
		com.covoiturage.District _districtID) {

		this.setCommuneID(_communeID);
		this.setDistrictID(_districtID);
		initialize();
	}

	protected void initialize () {}



	/**
	 * Return the unique identifier of this class
     * @hibernate.id
     *  generator-class="identity"
     *  column="CommuneID"
     */
	public java.lang.Integer getCommuneID () {
		return _communeID;
	}

	/**
	 * Set the unique identifier of this class
	 * @param _communeID the new ID
	 */
	public void setCommuneID (java.lang.Integer _communeID) {
		this._communeID = _communeID;
		this.hashCode = Integer.MIN_VALUE;
	}


	/**
	 * Return the value associated with the column: Nom
	 */
	public java.lang.String getNom () {
		return _nom;
	}

	/**
	 * Set the value related to the column: Nom
	 * @param _nom the Nom value
	 */
	public void setNom (java.lang.String _nom) {
		this._nom = _nom;
	}


	/**
     * @hibernate.property
     *  column=DistrictID
	 * not-null=true
	 */
	public com.covoiturage.District getDistrictID () {
		return this._districtID;
	}

	/**
	 * Set the value related to the column: DistrictID
	 * @param _districtID the DistrictID value
	 */
	public void setDistrictID (com.covoiturage.District _districtID) {
		this._districtID = _districtID;
	}


	/**
	 * Return the value associated with the column: RueSet
	 */
	public java.util.Set getRueSet () {
		return this._rueSet;
	}

	/**
	 * Set the value related to the column: RueSet
	 * @param _rueSet the RueSet value
	 */
	public void setRueSet (java.util.Set _rueSet) {
		this._rueSet = _rueSet;
	}
	
	public void addToRueSet (Object obj) {
		if (null == this._rueSet) this._rueSet = new java.util.HashSet();
		this._rueSet.add(obj);
	}



	public boolean equals (Object obj) {
		if (null == obj) return false;
		if (!(obj instanceof com.covoiturage.base.BaseCommune)) return false;
		else {
			com.covoiturage.base.BaseCommune mObj = (com.covoiturage.base.BaseCommune) obj;
			if (null == this.getCommuneID() || null == mObj.getCommuneID()) return false;
			else return (this.getCommuneID().equals(mObj.getCommuneID()));
		}
	}


	public int hashCode () {
		if (Integer.MIN_VALUE == this.hashCode) {
			if (null == this.getCommuneID()) return super.hashCode();
			else {
				String hashStr = this.getClass().getName() + ":" + this.getCommuneID().hashCode();
				this.hashCode = hashStr.hashCode();
			}
		}
		return this.hashCode;
	}


	public String toString () {
		return super.toString();
	}

}