package com.covoiturage.base;

import org.hibernate.Hibernate;
import org.hibernate.Session;
import com.covoiturage.dao.CompteDAO;

/**
 * This class has been automatically generated by Hibernate Synchronizer.
 * For more information or documentation, visit The Hibernate Synchronizer page
 * at http://www.binamics.com/hibernatesync or contact Joe Hudson at joe@binamics.com.
 *
 * This is an automatically generated DAO class which should not be edited.
 */
public abstract class BaseCompteDAO extends com.covoiturage.dao._RootDAO {

	public static CompteDAO instance;

	/**
	 * Return a singleton of the DAO
	 */
	public static CompteDAO getInstance () {
		if (null == instance) instance = new CompteDAO();
		return instance;
	}

	/**
	 * com.covoiturage.dao._RootDAO _RootDAO.getReferenceClass()
	 */
	public Class getReferenceClass () {
		return com.covoiturage.Compte.class;
	}
	
	public com.covoiturage.Compte load(java.lang.String key)
		throws org.hibernate.HibernateException {
		return (com.covoiturage.Compte) load(getReferenceClass(), key);
	}

	public com.covoiturage.Compte load(java.lang.String key, Session s)
		throws org.hibernate.HibernateException {
		return (com.covoiturage.Compte) load(getReferenceClass(), key, s);
	}

	public com.covoiturage.Compte loadInitialize(java.lang.String key, Session s) 
			throws org.hibernate.HibernateException { 
		com.covoiturage.Compte obj = load(key, s); 
		if (!Hibernate.isInitialized(obj)) {
			Hibernate.initialize(obj);
		} 
		return obj; 
	}

	/**
	 * Persist the given transient instance, first assigning a generated identifier. (Or using the current value
	 * of the identifier property if the assigned generator is used.) 
	 * @param compte a transient instance of a persistent class 
	 * @return the class identifier
	 */
	public java.lang.String save(com.covoiturage.Compte compte)
		throws org.hibernate.HibernateException {
		return (java.lang.String) super.save(compte);
	}

	/**
	 * Persist the given transient instance, first assigning a generated identifier. (Or using the current value
	 * of the identifier property if the assigned generator is used.) 
	 * Use the Session given.
	 * @param compte a transient instance of a persistent class
	 * @param s the Session
	 * @return the class identifier
	 */
	public java.lang.String save(com.covoiturage.Compte compte, Session s)
		throws org.hibernate.HibernateException {
		return (java.lang.String) super.save(compte, s);
	}

	/**
	 * Either save() or update() the given instance, depending upon the value of its identifier property. By default
	 * the instance is always saved. This behaviour may be adjusted by specifying an unsaved-value attribute of the
	 * identifier property mapping. 
	 * @param compte a transient instance containing new or updated state 
	 */
	public void saveOrUpdate(com.covoiturage.Compte compte)
		throws org.hibernate.HibernateException {
		super.saveOrUpdate(compte);
	}

	/**
	 * Either save() or update() the given instance, depending upon the value of its identifier property. By default the
	 * instance is always saved. This behaviour may be adjusted by specifying an unsaved-value attribute of the identifier
	 * property mapping. 
	 * Use the Session given.
	 * @param compte a transient instance containing new or updated state.
	 * @param s the Session.
	 */
	public void saveOrUpdate(com.covoiturage.Compte compte, Session s)
		throws org.hibernate.HibernateException {
		super.saveOrUpdate(compte, s);
	}

	/**
	 * Update the persistent state associated with the given identifier. An exception is thrown if there is a persistent
	 * instance with the same identifier in the current session.
	 * @param compte a transient instance containing updated state
	 */
	public void update(com.covoiturage.Compte compte) 
		throws org.hibernate.HibernateException {
		super.update(compte);
	}

	/**
	 * Update the persistent state associated with the given identifier. An exception is thrown if there is a persistent
	 * instance with the same identifier in the current session.
	 * Use the Session given.
	 * @param compte a transient instance containing updated state
	 * @param the Session
	 */
	public void update(com.covoiturage.Compte compte, Session s)
		throws org.hibernate.HibernateException {
		super.update(compte, s);
	}

	/**
	 * Remove a persistent instance from the datastore. The argument may be an instance associated with the receiving
	 * Session or a transient instance with an identifier associated with existing persistent state. 
	 * @param id the instance ID to be removed
	 */
	public void delete(java.lang.String id)
		throws org.hibernate.HibernateException {
		super.delete(load(id));
	}

	/**
	 * Remove a persistent instance from the datastore. The argument may be an instance associated with the receiving
	 * Session or a transient instance with an identifier associated with existing persistent state. 
	 * Use the Session given.
	 * @param id the instance ID to be removed
	 * @param s the Session
	 */
	public void delete(java.lang.String id, Session s)
		throws org.hibernate.HibernateException {
		super.delete(load(id, s), s);
	}

	/**
	 * Remove a persistent instance from the datastore. The argument may be an instance associated with the receiving
	 * Session or a transient instance with an identifier associated with existing persistent state. 
	 * @param compte the instance to be removed
	 */
	public void delete(com.covoiturage.Compte compte)
		throws org.hibernate.HibernateException {
		super.delete(compte);
	}

	/**
	 * Remove a persistent instance from the datastore. The argument may be an instance associated with the receiving
	 * Session or a transient instance with an identifier associated with existing persistent state. 
	 * Use the Session given.
	 * @param compte the instance to be removed
	 * @param s the Session
	 */
	public void delete(com.covoiturage.Compte compte, Session s)
		throws org.hibernate.HibernateException {
		super.delete(compte, s);
	}
	
	/**
	 * Re-read the state of the given instance from the underlying database. It is inadvisable to use this to implement
	 * long-running sessions that span many business tasks. This method is, however, useful in certain special circumstances.
	 * For example 
	 * <ul> 
	 * <li>where a database trigger alters the object state upon insert or update</li>
	 * <li>after executing direct SQL (eg. a mass update) in the same session</li>
	 * <li>after inserting a Blob or Clob</li>
	 * </ul>
	 */
	public void refresh (com.covoiturage.Compte compte, Session s)
		throws org.hibernate.HibernateException {
		super.refresh(compte, s);
	}

    public String getDefaultOrderProperty () {
		return null;
    }

}