package com.covoiturage.base;

import java.io.Serializable;


/**
 * This class has been automatically generated by Hibernate Synchronizer.
 * For more information or documentation, visit The Hibernate Synchronizer page
 * at http://www.binamics.com/hibernatesync or contact Joe Hudson at joe@binamics.com.
 *
 * This is an object that contains data related to the pointrencontre table.
 * Do not modify this class because it will be overwritten if the configuration file
 * related to this class is modified.
 *
 * @hibernate.class
 *  table="pointrencontre"
 */
public abstract class BasePointrencontre  implements Serializable {

	public static String PROP_NOM = "Nom";
	public static String PROP_DATE_CREATE = "DateCreate";
	public static String PROP_POINT_RENCONTRE_I_D = "PointRencontreID";
	public static String PROP_ADRESSE_I_D = "AdresseID";


	private int hashCode = Integer.MIN_VALUE;

	// primary key
	private java.lang.Integer _pointRencontreID;

	// fields
	private java.lang.String _nom;
	private java.util.Date _dateCreate;

	// many to one
	private com.covoiturage.Adresse _adresseID;

	// collections
	private java.util.Set _annonceSetByPointArriveeID;
	private java.util.Set _annonceSetByPointDepartID;


	// constructors
	public BasePointrencontre () {
		initialize();
	}

	/**
	 * Constructor for primary key
	 */
	public BasePointrencontre (java.lang.Integer _pointRencontreID) {
		this.setPointRencontreID(_pointRencontreID);
		initialize();
	}

	/**
	 * Constructor for required fields
	 */
	public BasePointrencontre (
		java.lang.Integer _pointRencontreID,
		com.covoiturage.Adresse _adresseID) {

		this.setPointRencontreID(_pointRencontreID);
		this.setAdresseID(_adresseID);
		initialize();
	}

	protected void initialize () {}



	/**
	 * Return the unique identifier of this class
     * @hibernate.id
     *  generator-class="identity"
     *  column="PointRencontreID"
     */
	public java.lang.Integer getPointRencontreID () {
		return _pointRencontreID;
	}

	/**
	 * Set the unique identifier of this class
	 * @param _pointRencontreID the new ID
	 */
	public void setPointRencontreID (java.lang.Integer _pointRencontreID) {
		this._pointRencontreID = _pointRencontreID;
		this.hashCode = Integer.MIN_VALUE;
	}


	/**
	 * Return the value associated with the column: Nom
	 */
	public java.lang.String getNom () {
		return _nom;
	}

	/**
	 * Set the value related to the column: Nom
	 * @param _nom the Nom value
	 */
	public void setNom (java.lang.String _nom) {
		this._nom = _nom;
	}


	/**
	 * Return the value associated with the column: DateCreate
	 */
	public java.util.Date getDateCreate () {
		return _dateCreate;
	}

	/**
	 * Set the value related to the column: DateCreate
	 * @param _dateCreate the DateCreate value
	 */
	public void setDateCreate (java.util.Date _dateCreate) {
		this._dateCreate = _dateCreate;
	}


	/**
     * @hibernate.property
     *  column=AdresseID
	 * not-null=true
	 */
	public com.covoiturage.Adresse getAdresseID () {
		return this._adresseID;
	}

	/**
	 * Set the value related to the column: AdresseID
	 * @param _adresseID the AdresseID value
	 */
	public void setAdresseID (com.covoiturage.Adresse _adresseID) {
		this._adresseID = _adresseID;
	}


	/**
	 * Return the value associated with the column: AnnonceSetByPointArriveeID
	 */
	public java.util.Set getAnnonceSetByPointArriveeID () {
		return this._annonceSetByPointArriveeID;
	}

	/**
	 * Set the value related to the column: AnnonceSetByPointArriveeID
	 * @param _annonceSetByPointArriveeID the AnnonceSetByPointArriveeID value
	 */
	public void setAnnonceSetByPointArriveeID (java.util.Set _annonceSetByPointArriveeID) {
		this._annonceSetByPointArriveeID = _annonceSetByPointArriveeID;
	}
	
	public void addToAnnonceSetByPointArriveeID (Object obj) {
		if (null == this._annonceSetByPointArriveeID) this._annonceSetByPointArriveeID = new java.util.HashSet();
		this._annonceSetByPointArriveeID.add(obj);
	}



	/**
	 * Return the value associated with the column: AnnonceSetByPointDepartID
	 */
	public java.util.Set getAnnonceSetByPointDepartID () {
		return this._annonceSetByPointDepartID;
	}

	/**
	 * Set the value related to the column: AnnonceSetByPointDepartID
	 * @param _annonceSetByPointDepartID the AnnonceSetByPointDepartID value
	 */
	public void setAnnonceSetByPointDepartID (java.util.Set _annonceSetByPointDepartID) {
		this._annonceSetByPointDepartID = _annonceSetByPointDepartID;
	}
	
	public void addToAnnonceSetByPointDepartID (Object obj) {
		if (null == this._annonceSetByPointDepartID) this._annonceSetByPointDepartID = new java.util.HashSet();
		this._annonceSetByPointDepartID.add(obj);
	}



	public boolean equals (Object obj) {
		if (null == obj) return false;
		if (!(obj instanceof com.covoiturage.base.BasePointrencontre)) return false;
		else {
			com.covoiturage.base.BasePointrencontre mObj = (com.covoiturage.base.BasePointrencontre) obj;
			if (null == this.getPointRencontreID() || null == mObj.getPointRencontreID()) return false;
			else return (this.getPointRencontreID().equals(mObj.getPointRencontreID()));
		}
	}


	public int hashCode () {
		if (Integer.MIN_VALUE == this.hashCode) {
			if (null == this.getPointRencontreID()) return super.hashCode();
			else {
				String hashStr = this.getClass().getName() + ":" + this.getPointRencontreID().hashCode();
				this.hashCode = hashStr.hashCode();
			}
		}
		return this.hashCode;
	}


	public String toString () {
		return super.toString();
	}

}