package com.covoiturage.base;

import java.io.Serializable;


/**
 * This class has been automatically generated by Hibernate Synchronizer.
 * For more information or documentation, visit The Hibernate Synchronizer page
 * at http://www.binamics.com/hibernatesync or contact Joe Hudson at joe@binamics.com.
 *
 * This is an object that contains data related to the annonce_utilisateur table.
 * Do not modify this class because it will be overwritten if the configuration file
 * related to this class is modified.
 *
 * @hibernate.class
 *  table="annonce_utilisateur"
 */
public abstract class BaseAnnonceUtilisateur  extends com.covoiturage.Annonce  implements Serializable {

	public static String PROP_VOITURE_I_D = "VoitureID";
	public static String PROP_UTILISATEUR_I_D = "UtilisateurID";
	public static String PROP_ANNONCE_I_D = "AnnonceID";


	private int hashCode = Integer.MIN_VALUE;

	// primary key
	private java.lang.Integer _annonceID;

	// many to one
	private com.covoiturage.Utilisateur _utilisateurID;
	private com.covoiturage.Voiture _voitureID;


	// constructors
	public BaseAnnonceUtilisateur () {
		initialize();
	}

	/**
	 * Constructor for primary key
	 */
	public BaseAnnonceUtilisateur (java.lang.Integer _annonceID) {
		super(_annonceID);
	}

	/**
	 * Constructor for required fields
	 */
	public BaseAnnonceUtilisateur (
		java.lang.Integer _annonceID,
		com.covoiturage.Utilisateur _utilisateurID,
		com.covoiturage.Pointrencontre _pointDepartID,
		com.covoiturage.Pointrencontre _pointArriveeID) {

		super (
			_annonceID,
			_utilisateurID,
			_pointDepartID,
			_pointArriveeID);
	}



	/**
	 * Return the unique identifier of this class
     * @hibernate.id
     *  generator-class="identity"
     *  column="AnnonceID"
     */
	public java.lang.Integer getAnnonceID () {
		return _annonceID;
	}

	/**
	 * Set the unique identifier of this class
	 * @param _annonceID the new ID
	 */
	public void setAnnonceID (java.lang.Integer _annonceID) {
		this._annonceID = _annonceID;
		this.hashCode = Integer.MIN_VALUE;
	}


	/**
     * @hibernate.property
     *  column=UtilisateurID
	 * not-null=true
	 */
	public com.covoiturage.Utilisateur getUtilisateurID () {
		return this._utilisateurID;
	}

	/**
	 * Set the value related to the column: UtilisateurID
	 * @param _utilisateurID the UtilisateurID value
	 */
	public void setUtilisateurID (com.covoiturage.Utilisateur _utilisateurID) {
		this._utilisateurID = _utilisateurID;
	}


	/**
     * @hibernate.property
     *  column=VoitureID
	 * not-null=true
	 */
	public com.covoiturage.Voiture getVoitureID () {
		return this._voitureID;
	}

	/**
	 * Set the value related to the column: VoitureID
	 * @param _voitureID the VoitureID value
	 */
	public void setVoitureID (com.covoiturage.Voiture _voitureID) {
		this._voitureID = _voitureID;
	}


	public boolean equals (Object obj) {
		if (null == obj) return false;
		if (!(obj instanceof com.covoiturage.base.BaseAnnonceUtilisateur)) return false;
		else {
			com.covoiturage.base.BaseAnnonceUtilisateur mObj = (com.covoiturage.base.BaseAnnonceUtilisateur) obj;
			if (null == this.getAnnonceID() || null == mObj.getAnnonceID()) return false;
			else return (this.getAnnonceID().equals(mObj.getAnnonceID()));
		}
	}


	public int hashCode () {
		if (Integer.MIN_VALUE == this.hashCode) {
			if (null == this.getAnnonceID()) return super.hashCode();
			else {
				String hashStr = this.getClass().getName() + ":" + this.getAnnonceID().hashCode();
				this.hashCode = hashStr.hashCode();
			}
		}
		return this.hashCode;
	}


	public String toString () {
		return super.toString();
	}

}