package com.covoiturage.base;

import java.io.Serializable;


/**
 * This class has been automatically generated by Hibernate Synchronizer.
 * For more information or documentation, visit The Hibernate Synchronizer page
 * at http://www.binamics.com/hibernatesync or contact Joe Hudson at joe@binamics.com.
 *
 * This is an object that contains data related to the adresse table.
 * Do not modify this class because it will be overwritten if the configuration file
 * related to this class is modified.
 *
 * @hibernate.class
 *  table="adresse"
 */
public abstract class BaseAdresse  implements Serializable {

	public static String PROP_VILLE_I_D = "VilleID";
	public static String PROP_ADRESSE_I_D = "AdresseID";


	private int hashCode = Integer.MIN_VALUE;

	// primary key
	private java.lang.Integer _adresseID;

	// fields
	private com.covoiturage.Ville _villeID;

	// collections
	private java.util.Set _pointrencontreSet;


	// constructors
	public BaseAdresse () {
		initialize();
	}

	/**
	 * Constructor for primary key
	 */
	public BaseAdresse (java.lang.Integer _adresseID) {
		this.setAdresseID(_adresseID);
		initialize();
	}

	/**
	 * Constructor for required fields
	 */
	public BaseAdresse (
		java.lang.Integer _adresseID,
		com.covoiturage.Ville _villeID) {

		this.setAdresseID(_adresseID);
		this.setVilleID(_villeID);
		initialize();
	}

	protected void initialize () {}



	/**
	 * Return the unique identifier of this class
     * @hibernate.id
     *  generator-class="identity"
     *  column="AdresseID"
     */
	public java.lang.Integer getAdresseID () {
		return _adresseID;
	}

	/**
	 * Set the unique identifier of this class
	 * @param _adresseID the new ID
	 */
	public void setAdresseID (java.lang.Integer _adresseID) {
		this._adresseID = _adresseID;
		this.hashCode = Integer.MIN_VALUE;
	}


	/**
	 * Return the value associated with the column: VilleID
	 */
	public com.covoiturage.Ville getVilleID () {
		return _villeID;
	}

	/**
	 * Set the value related to the column: VilleID
	 * @param _villeID the VilleID value
	 */
	public void setVilleID (com.covoiturage.Ville _villeID) {
		this._villeID = _villeID;
	}


	/**
	 * Return the value associated with the column: PointrencontreSet
	 */
	public java.util.Set getPointrencontreSet () {
		return this._pointrencontreSet;
	}

	/**
	 * Set the value related to the column: PointrencontreSet
	 * @param _pointrencontreSet the PointrencontreSet value
	 */
	public void setPointrencontreSet (java.util.Set _pointrencontreSet) {
		this._pointrencontreSet = _pointrencontreSet;
	}
	
	public void addToPointrencontreSet (Object obj) {
		if (null == this._pointrencontreSet) this._pointrencontreSet = new java.util.HashSet();
		this._pointrencontreSet.add(obj);
	}



	public boolean equals (Object obj) {
		if (null == obj) return false;
		if (!(obj instanceof com.covoiturage.base.BaseAdresse)) return false;
		else {
			com.covoiturage.base.BaseAdresse mObj = (com.covoiturage.base.BaseAdresse) obj;
			if (null == this.getAdresseID() || null == mObj.getAdresseID()) return false;
			else return (this.getAdresseID().equals(mObj.getAdresseID()));
		}
	}


	public int hashCode () {
		if (Integer.MIN_VALUE == this.hashCode) {
			if (null == this.getAdresseID()) return super.hashCode();
			else {
				String hashStr = this.getClass().getName() + ":" + this.getAdresseID().hashCode();
				this.hashCode = hashStr.hashCode();
			}
		}
		return this.hashCode;
	}


	public String toString () {
		return super.toString();
	}

}