package com.covoiturage.base;

import java.io.Serializable;


/**
 * This class has been automatically generated by Hibernate Synchronizer.
 * For more information or documentation, visit The Hibernate Synchronizer page
 * at http://www.binamics.com/hibernatesync or contact Joe Hudson at joe@binamics.com.
 *
 * This is an object that contains data related to the annonce table.
 * Do not modify this class because it will be overwritten if the configuration file
 * related to this class is modified.
 *
 * @hibernate.class
 *  table="annonce"
 */
public abstract class BaseAnnonce  implements Serializable {

	public static String PROP_DESCRIPTION = "Description";
	public static String PROP_DATE_UPDATE = "DateUpdate";
	public static String PROP_DATE_DEPART = "DateDepart";
	public static String PROP_UTILISATEUR_I_D = "UtilisateurID";
	public static String PROP_ANNONCE_I_D = "AnnonceID";
	public static String PROP_POINT_ARRIVEE_I_D = "PointArriveeID";
	public static String PROP_HEURE_DEPART = "HeureDepart";
	public static String PROP_DATE_ARRIVEE = "DateArrivee";
	public static String PROP_POINT_DEPART_I_D = "PointDepartID";
	public static String PROP_DATE_CREATE = "DateCreate";
	public static String PROP_HEURE_ARRIVEE = "HeureArrivee";


	private int hashCode = Integer.MIN_VALUE;

	// primary key
	private java.lang.Integer _annonceID;

	// fields
	private java.util.Date _dateUpdate;
	private java.lang.String _description;
	private java.util.Date _dateDepart;
	private java.lang.String _heureDepart;
	private java.util.Date _dateArrivee;
	private java.util.Date _dateCreate;
	private java.lang.String _heureArrivee;

	// many to one
	private com.covoiturage.Utilisateur _utilisateurID;
	private com.covoiturage.Pointrencontre _pointDepartID;
	private com.covoiturage.Pointrencontre _pointArriveeID;


	// constructors
	public BaseAnnonce () {
		initialize();
	}

	/**
	 * Constructor for primary key
	 */
	public BaseAnnonce (java.lang.Integer _annonceID) {
		this.setAnnonceID(_annonceID);
		initialize();
	}

	/**
	 * Constructor for required fields
	 */
	public BaseAnnonce (
		java.lang.Integer _annonceID,
		com.covoiturage.Utilisateur _utilisateurID,
		com.covoiturage.Pointrencontre _pointDepartID,
		com.covoiturage.Pointrencontre _pointArriveeID) {

		this.setAnnonceID(_annonceID);
		this.setUtilisateurID(_utilisateurID);
		this.setPointDepartID(_pointDepartID);
		this.setPointArriveeID(_pointArriveeID);
		initialize();
	}

	protected void initialize () {}



	/**
	 * Return the unique identifier of this class
     * @hibernate.id
     *  generator-class="identity"
     *  column="AnnonceID"
     */
	public java.lang.Integer getAnnonceID () {
		return _annonceID;
	}

	/**
	 * Set the unique identifier of this class
	 * @param _annonceID the new ID
	 */
	public void setAnnonceID (java.lang.Integer _annonceID) {
		this._annonceID = _annonceID;
		this.hashCode = Integer.MIN_VALUE;
	}


	/**
	 * Return the value associated with the column: DateUpdate
	 */
	public java.util.Date getDateUpdate () {
		return _dateUpdate;
	}

	/**
	 * Set the value related to the column: DateUpdate
	 * @param _dateUpdate the DateUpdate value
	 */
	public void setDateUpdate (java.util.Date _dateUpdate) {
		this._dateUpdate = _dateUpdate;
	}


	/**
	 * Return the value associated with the column: Description
	 */
	public java.lang.String getDescription () {
		return _description;
	}

	/**
	 * Set the value related to the column: Description
	 * @param _description the Description value
	 */
	public void setDescription (java.lang.String _description) {
		this._description = _description;
	}


	/**
	 * Return the value associated with the column: DateDepart
	 */
	public java.util.Date getDateDepart () {
		return _dateDepart;
	}

	/**
	 * Set the value related to the column: DateDepart
	 * @param _dateDepart the DateDepart value
	 */
	public void setDateDepart (java.util.Date _dateDepart) {
		this._dateDepart = _dateDepart;
	}


	/**
	 * Return the value associated with the column: HeureDepart
	 */
	public java.lang.String getHeureDepart () {
		return _heureDepart;
	}

	/**
	 * Set the value related to the column: HeureDepart
	 * @param _heureDepart the HeureDepart value
	 */
	public void setHeureDepart (java.lang.String _heureDepart) {
		this._heureDepart = _heureDepart;
	}


	/**
	 * Return the value associated with the column: DateArrivee
	 */
	public java.util.Date getDateArrivee () {
		return _dateArrivee;
	}

	/**
	 * Set the value related to the column: DateArrivee
	 * @param _dateArrivee the DateArrivee value
	 */
	public void setDateArrivee (java.util.Date _dateArrivee) {
		this._dateArrivee = _dateArrivee;
	}


	/**
	 * Return the value associated with the column: DateCreate
	 */
	public java.util.Date getDateCreate () {
		return _dateCreate;
	}

	/**
	 * Set the value related to the column: DateCreate
	 * @param _dateCreate the DateCreate value
	 */
	public void setDateCreate (java.util.Date _dateCreate) {
		this._dateCreate = _dateCreate;
	}


	/**
	 * Return the value associated with the column: HeureArrivee
	 */
	public java.lang.String getHeureArrivee () {
		return _heureArrivee;
	}

	/**
	 * Set the value related to the column: HeureArrivee
	 * @param _heureArrivee the HeureArrivee value
	 */
	public void setHeureArrivee (java.lang.String _heureArrivee) {
		this._heureArrivee = _heureArrivee;
	}


	/**
     * @hibernate.property
     *  column=UtilisateurID
	 * not-null=true
	 */
	public com.covoiturage.Utilisateur getUtilisateurID () {
		return this._utilisateurID;
	}

	/**
	 * Set the value related to the column: UtilisateurID
	 * @param _utilisateurID the UtilisateurID value
	 */
	public void setUtilisateurID (com.covoiturage.Utilisateur _utilisateurID) {
		this._utilisateurID = _utilisateurID;
	}


	/**
     * @hibernate.property
     *  column=PointDepartID
	 * not-null=true
	 */
	public com.covoiturage.Pointrencontre getPointDepartID () {
		return this._pointDepartID;
	}

	/**
	 * Set the value related to the column: PointDepartID
	 * @param _pointDepartID the PointDepartID value
	 */
	public void setPointDepartID (com.covoiturage.Pointrencontre _pointDepartID) {
		this._pointDepartID = _pointDepartID;
	}


	/**
     * @hibernate.property
     *  column=PointArriveeID
	 * not-null=true
	 */
	public com.covoiturage.Pointrencontre getPointArriveeID () {
		return this._pointArriveeID;
	}

	/**
	 * Set the value related to the column: PointArriveeID
	 * @param _pointArriveeID the PointArriveeID value
	 */
	public void setPointArriveeID (com.covoiturage.Pointrencontre _pointArriveeID) {
		this._pointArriveeID = _pointArriveeID;
	}


	public boolean equals (Object obj) {
		if (null == obj) return false;
		if (!(obj instanceof com.covoiturage.base.BaseAnnonce)) return false;
		else {
			com.covoiturage.base.BaseAnnonce mObj = (com.covoiturage.base.BaseAnnonce) obj;
			if (null == this.getAnnonceID() || null == mObj.getAnnonceID()) return false;
			else return (this.getAnnonceID().equals(mObj.getAnnonceID()));
		}
	}


	public int hashCode () {
		if (Integer.MIN_VALUE == this.hashCode) {
			if (null == this.getAnnonceID()) return super.hashCode();
			else {
				String hashStr = this.getClass().getName() + ":" + this.getAnnonceID().hashCode();
				this.hashCode = hashStr.hashCode();
			}
		}
		return this.hashCode;
	}


	public String toString () {
		return super.toString();
	}

}