package com.covoiturage.base;

import java.io.Serializable;


/**
 * This class has been automatically generated by Hibernate Synchronizer.
 * For more information or documentation, visit The Hibernate Synchronizer page
 * at http://www.binamics.com/hibernatesync or contact Joe Hudson at joe@binamics.com.
 *
 * This is an object that contains data related to the voiture table.
 * Do not modify this class because it will be overwritten if the configuration file
 * related to this class is modified.
 *
 * @hibernate.class
 *  table="voiture"
 */
public abstract class BaseVoiture  implements Serializable {

	public static String PROP_VOITURE_I_D = "VoitureID";
	public static String PROP_TYPE = "Type";
	public static String PROP_UTILISATEUR_I_D = "UtilisateurID";
	public static String PROP_NOMBRE_PLACE = "NombrePlace";


	private int hashCode = Integer.MIN_VALUE;

	// primary key
	private java.lang.Integer _voitureID;

	// fields
	private java.lang.String _type;
	private java.lang.Integer _nombrePlace;

	// many to one
	private com.covoiturage.Utilisateur _utilisateurID;

	// collections
	private java.util.Set _annonceUtilisateurSet;


	// constructors
	public BaseVoiture () {
		initialize();
	}

	/**
	 * Constructor for primary key
	 */
	public BaseVoiture (java.lang.Integer _voitureID) {
		this.setVoitureID(_voitureID);
		initialize();
	}

	/**
	 * Constructor for required fields
	 */
	public BaseVoiture (
		java.lang.Integer _voitureID,
		com.covoiturage.Utilisateur _utilisateurID) {

		this.setVoitureID(_voitureID);
		this.setUtilisateurID(_utilisateurID);
		initialize();
	}

	protected void initialize () {}



	/**
	 * Return the unique identifier of this class
     * @hibernate.id
     *  generator-class="identity"
     *  column="VoitureID"
     */
	public java.lang.Integer getVoitureID () {
		return _voitureID;
	}

	/**
	 * Set the unique identifier of this class
	 * @param _voitureID the new ID
	 */
	public void setVoitureID (java.lang.Integer _voitureID) {
		this._voitureID = _voitureID;
		this.hashCode = Integer.MIN_VALUE;
	}


	/**
	 * Return the value associated with the column: Type
	 */
	public java.lang.String getType () {
		return _type;
	}

	/**
	 * Set the value related to the column: Type
	 * @param _type the Type value
	 */
	public void setType (java.lang.String _type) {
		this._type = _type;
	}


	/**
	 * Return the value associated with the column: NombrePlace
	 */
	public java.lang.Integer getNombrePlace () {
		return _nombrePlace;
	}

	/**
	 * Set the value related to the column: NombrePlace
	 * @param _nombrePlace the NombrePlace value
	 */
	public void setNombrePlace (java.lang.Integer _nombrePlace) {
		this._nombrePlace = _nombrePlace;
	}


	/**
     * @hibernate.property
     *  column=UtilisateurID
	 * not-null=true
	 */
	public com.covoiturage.Utilisateur getUtilisateurID () {
		return this._utilisateurID;
	}

	/**
	 * Set the value related to the column: UtilisateurID
	 * @param _utilisateurID the UtilisateurID value
	 */
	public void setUtilisateurID (com.covoiturage.Utilisateur _utilisateurID) {
		this._utilisateurID = _utilisateurID;
	}


	/**
	 * Return the value associated with the column: AnnonceUtilisateurSet
	 */
	public java.util.Set getAnnonceUtilisateurSet () {
		return this._annonceUtilisateurSet;
	}

	/**
	 * Set the value related to the column: AnnonceUtilisateurSet
	 * @param _annonceUtilisateurSet the AnnonceUtilisateurSet value
	 */
	public void setAnnonceUtilisateurSet (java.util.Set _annonceUtilisateurSet) {
		this._annonceUtilisateurSet = _annonceUtilisateurSet;
	}
	
	public void addToAnnonceUtilisateurSet (Object obj) {
		if (null == this._annonceUtilisateurSet) this._annonceUtilisateurSet = new java.util.HashSet();
		this._annonceUtilisateurSet.add(obj);
	}



	public boolean equals (Object obj) {
		if (null == obj) return false;
		if (!(obj instanceof com.covoiturage.base.BaseVoiture)) return false;
		else {
			com.covoiturage.base.BaseVoiture mObj = (com.covoiturage.base.BaseVoiture) obj;
			if (null == this.getVoitureID() || null == mObj.getVoitureID()) return false;
			else return (this.getVoitureID().equals(mObj.getVoitureID()));
		}
	}


	public int hashCode () {
		if (Integer.MIN_VALUE == this.hashCode) {
			if (null == this.getVoitureID()) return super.hashCode();
			else {
				String hashStr = this.getClass().getName() + ":" + this.getVoitureID().hashCode();
				this.hashCode = hashStr.hashCode();
			}
		}
		return this.hashCode;
	}


	public String toString () {
		return super.toString();
	}

}