package com.covoiturage.base;

import java.io.Serializable;


/**
 * This class has been automatically generated by Hibernate Synchronizer.
 * For more information or documentation, visit The Hibernate Synchronizer page
 * at http://www.binamics.com/hibernatesync or contact Joe Hudson at joe@binamics.com.
 *
 * This is an object that contains data related to the utilisateur table.
 * Do not modify this class because it will be overwritten if the configuration file
 * related to this class is modified.
 *
 * @hibernate.class
 *  table="utilisateur"
 */
public abstract class BaseUtilisateur  implements Serializable {

	public static String PROP_DATE_NAISSANCE = "DateNaissance";
	public static String PROP_NOM = "Nom";
	public static String PROP_DATE_UPDATE = "DateUpdate";
	public static String PROP_TELEPHONE = "Telephone";
	public static String PROP_EMAIL = "Email";
	public static String PROP_UTILISATEUR_I_D = "UtilisateurID";
	public static String PROP_PRENOM = "Prenom";
	public static String PROP_DATE_CREATE = "DateCreate";


	private int hashCode = Integer.MIN_VALUE;

	// primary key
	private java.lang.Integer _utilisateurID;

	// fields
	private java.util.Date _dateNaissance;
	private java.lang.String _nom;
	private java.util.Date _dateUpdate;
	private java.lang.String _email;
	private java.lang.String _telephone;
	private java.lang.String _prenom;
	private java.util.Date _dateCreate;

	// collections
	private java.util.Set _voitureSet;
	private java.util.Set _annonceSet;
	private java.util.Set _annonceUtilisateurSet;
	private java.util.Set _compteSet;


	// constructors
	public BaseUtilisateur () {
		initialize();
	}

	/**
	 * Constructor for primary key
	 */
	public BaseUtilisateur (java.lang.Integer _utilisateurID) {
		this.setUtilisateurID(_utilisateurID);
		initialize();
	}

	protected void initialize () {}



	/**
	 * Return the unique identifier of this class
     * @hibernate.id
     *  generator-class="identity"
     *  column="UtilisateurID"
     */
	public java.lang.Integer getUtilisateurID () {
		return _utilisateurID;
	}

	/**
	 * Set the unique identifier of this class
	 * @param _utilisateurID the new ID
	 */
	public void setUtilisateurID (java.lang.Integer _utilisateurID) {
		this._utilisateurID = _utilisateurID;
		this.hashCode = Integer.MIN_VALUE;
	}


	/**
	 * Return the value associated with the column: DateNaissance
	 */
	public java.util.Date getDateNaissance () {
		return _dateNaissance;
	}

	/**
	 * Set the value related to the column: DateNaissance
	 * @param _dateNaissance the DateNaissance value
	 */
	public void setDateNaissance (java.util.Date _dateNaissance) {
		this._dateNaissance = _dateNaissance;
	}


	/**
	 * Return the value associated with the column: Nom
	 */
	public java.lang.String getNom () {
		return _nom;
	}

	/**
	 * Set the value related to the column: Nom
	 * @param _nom the Nom value
	 */
	public void setNom (java.lang.String _nom) {
		this._nom = _nom;
	}


	/**
	 * Return the value associated with the column: DateUpdate
	 */
	public java.util.Date getDateUpdate () {
		return _dateUpdate;
	}

	/**
	 * Set the value related to the column: DateUpdate
	 * @param _dateUpdate the DateUpdate value
	 */
	public void setDateUpdate (java.util.Date _dateUpdate) {
		this._dateUpdate = _dateUpdate;
	}


	/**
	 * Return the value associated with the column: Email
	 */
	public java.lang.String getEmail () {
		return _email;
	}

	/**
	 * Set the value related to the column: Email
	 * @param _email the Email value
	 */
	public void setEmail (java.lang.String _email) {
		this._email = _email;
	}


	/**
	 * Return the value associated with the column: Telephone
	 */
	public java.lang.String getTelephone () {
		return _telephone;
	}

	/**
	 * Set the value related to the column: Telephone
	 * @param _telephone the Telephone value
	 */
	public void setTelephone (java.lang.String _telephone) {
		this._telephone = _telephone;
	}


	/**
	 * Return the value associated with the column: Prenom
	 */
	public java.lang.String getPrenom () {
		return _prenom;
	}

	/**
	 * Set the value related to the column: Prenom
	 * @param _prenom the Prenom value
	 */
	public void setPrenom (java.lang.String _prenom) {
		this._prenom = _prenom;
	}


	/**
	 * Return the value associated with the column: DateCreate
	 */
	public java.util.Date getDateCreate () {
		return _dateCreate;
	}

	/**
	 * Set the value related to the column: DateCreate
	 * @param _dateCreate the DateCreate value
	 */
	public void setDateCreate (java.util.Date _dateCreate) {
		this._dateCreate = _dateCreate;
	}


	/**
	 * Return the value associated with the column: VoitureSet
	 */
	public java.util.Set getVoitureSet () {
		return this._voitureSet;
	}

	/**
	 * Set the value related to the column: VoitureSet
	 * @param _voitureSet the VoitureSet value
	 */
	public void setVoitureSet (java.util.Set _voitureSet) {
		this._voitureSet = _voitureSet;
	}
	
	public void addToVoitureSet (Object obj) {
		if (null == this._voitureSet) this._voitureSet = new java.util.HashSet();
		this._voitureSet.add(obj);
	}



	/**
	 * Return the value associated with the column: AnnonceSet
	 */
	public java.util.Set getAnnonceSet () {
		return this._annonceSet;
	}

	/**
	 * Set the value related to the column: AnnonceSet
	 * @param _annonceSet the AnnonceSet value
	 */
	public void setAnnonceSet (java.util.Set _annonceSet) {
		this._annonceSet = _annonceSet;
	}
	
	public void addToAnnonceSet (Object obj) {
		if (null == this._annonceSet) this._annonceSet = new java.util.HashSet();
		this._annonceSet.add(obj);
	}



	/**
	 * Return the value associated with the column: AnnonceUtilisateurSet
	 */
	public java.util.Set getAnnonceUtilisateurSet () {
		return this._annonceUtilisateurSet;
	}

	/**
	 * Set the value related to the column: AnnonceUtilisateurSet
	 * @param _annonceUtilisateurSet the AnnonceUtilisateurSet value
	 */
	public void setAnnonceUtilisateurSet (java.util.Set _annonceUtilisateurSet) {
		this._annonceUtilisateurSet = _annonceUtilisateurSet;
	}
	
	public void addToAnnonceUtilisateurSet (Object obj) {
		if (null == this._annonceUtilisateurSet) this._annonceUtilisateurSet = new java.util.HashSet();
		this._annonceUtilisateurSet.add(obj);
	}



	/**
	 * Return the value associated with the column: CompteSet
	 */
	public java.util.Set getCompteSet () {
		return this._compteSet;
	}

	/**
	 * Set the value related to the column: CompteSet
	 * @param _compteSet the CompteSet value
	 */
	public void setCompteSet (java.util.Set _compteSet) {
		this._compteSet = _compteSet;
	}
	
	public void addToCompteSet (Object obj) {
		if (null == this._compteSet) this._compteSet = new java.util.HashSet();
		this._compteSet.add(obj);
	}



	public boolean equals (Object obj) {
		if (null == obj) return false;
		if (!(obj instanceof com.covoiturage.base.BaseUtilisateur)) return false;
		else {
			com.covoiturage.base.BaseUtilisateur mObj = (com.covoiturage.base.BaseUtilisateur) obj;
			if (null == this.getUtilisateurID() || null == mObj.getUtilisateurID()) return false;
			else return (this.getUtilisateurID().equals(mObj.getUtilisateurID()));
		}
	}


	public int hashCode () {
		if (Integer.MIN_VALUE == this.hashCode) {
			if (null == this.getUtilisateurID()) return super.hashCode();
			else {
				String hashStr = this.getClass().getName() + ":" + this.getUtilisateurID().hashCode();
				this.hashCode = hashStr.hashCode();
			}
		}
		return this.hashCode;
	}


	public String toString () {
		return super.toString();
	}

}