package com.covoiturage.base;

import java.io.Serializable;


/**
 * This class has been automatically generated by Hibernate Synchronizer.
 * For more information or documentation, visit The Hibernate Synchronizer page
 * at http://www.binamics.com/hibernatesync or contact Joe Hudson at joe@binamics.com.
 *
 * This is an object that contains data related to the ville table.
 * Do not modify this class because it will be overwritten if the configuration file
 * related to this class is modified.
 *
 * @hibernate.class
 *  table="ville"
 */
public abstract class BaseVille  implements Serializable {

	public static String PROP_NOM = "Nom";
	public static String PROP_VILLE_I_D = "VilleID";


	private int hashCode = Integer.MIN_VALUE;

	// primary key
	private java.lang.Integer _villeID;

	// fields
	private java.lang.String _nom;

	// collections
	private java.util.Set _adresseSet;
	private java.util.Set _districtSet;


	// constructors
	public BaseVille () {
		initialize();
	}

	/**
	 * Constructor for primary key
	 */
	public BaseVille (java.lang.Integer _villeID) {
		this.setVilleID(_villeID);
		initialize();
	}

	protected void initialize () {}



	/**
	 * Return the unique identifier of this class
     * @hibernate.id
     *  generator-class="identity"
     *  column="VilleID"
     */
	public java.lang.Integer getVilleID () {
		return _villeID;
	}

	/**
	 * Set the unique identifier of this class
	 * @param _villeID the new ID
	 */
	public void setVilleID (java.lang.Integer _villeID) {
		this._villeID = _villeID;
		this.hashCode = Integer.MIN_VALUE;
	}


	/**
	 * Return the value associated with the column: Nom
	 */
	public java.lang.String getNom () {
		return _nom;
	}

	/**
	 * Set the value related to the column: Nom
	 * @param _nom the Nom value
	 */
	public void setNom (java.lang.String _nom) {
		this._nom = _nom;
	}


	/**
	 * Return the value associated with the column: AdresseSet
	 */
	public java.util.Set getAdresseSet () {
		return this._adresseSet;
	}

	/**
	 * Set the value related to the column: AdresseSet
	 * @param _adresseSet the AdresseSet value
	 */
	public void setAdresseSet (java.util.Set _adresseSet) {
		this._adresseSet = _adresseSet;
	}
	
	public void addToAdresseSet (Object obj) {
		if (null == this._adresseSet) this._adresseSet = new java.util.HashSet();
		this._adresseSet.add(obj);
	}



	/**
	 * Return the value associated with the column: DistrictSet
	 */
	public java.util.Set getDistrictSet () {
		return this._districtSet;
	}

	/**
	 * Set the value related to the column: DistrictSet
	 * @param _districtSet the DistrictSet value
	 */
	public void setDistrictSet (java.util.Set _districtSet) {
		this._districtSet = _districtSet;
	}
	
	public void addToDistrictSet (Object obj) {
		if (null == this._districtSet) this._districtSet = new java.util.HashSet();
		this._districtSet.add(obj);
	}



	public boolean equals (Object obj) {
		if (null == obj) return false;
		if (!(obj instanceof com.covoiturage.base.BaseVille)) return false;
		else {
			com.covoiturage.base.BaseVille mObj = (com.covoiturage.base.BaseVille) obj;
			if (null == this.getVilleID() || null == mObj.getVilleID()) return false;
			else return (this.getVilleID().equals(mObj.getVilleID()));
		}
	}


	public int hashCode () {
		if (Integer.MIN_VALUE == this.hashCode) {
			if (null == this.getVilleID()) return super.hashCode();
			else {
				String hashStr = this.getClass().getName() + ":" + this.getVilleID().hashCode();
				this.hashCode = hashStr.hashCode();
			}
		}
		return this.hashCode;
	}


	public String toString () {
		return super.toString();
	}

}